services:
  eqproxy-io:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 20.11.1
    env_file:
      - .env
    environment:
      - TZ=Asia/Tokyo
      - PORT=4000
    restart: always
    ports:
      # ws.api.eqmonitor.app
      - 4000:4000
      # Prometheus metrics
      - 4002:4002
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: '3'
  dmdata-proxy:
    build:
      context: .
      dockerfile: ./service/dmdata-proxy/Dockerfile
    env_file:
      - ./service/dmdata-proxy/.env
    environment:
      - TZ=Asia/Tokyo
      - WEBSOCKET_PORT=4020
    restart: always
    ports:
      - 4020:4020
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: '3'