services:
  eqproxy-io:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 20.11.1
    env_file:
      - .env
    environment:
      - TZ=Asia/Tokyo
      - PORT=4000
    restart: always
    ports:
      # ws.api.eqmonitor.app
      - 4000:4000
      # status.api.eqmonitor.app
      - 4001:4001
      # Prometheus metrics
      - 4002:4002
    #sysctls: