name: deploy
on:
  push:
    branches:
      - hoge
      #- main

jobs:
  deploy:
    runs-on: srv2-osaka-api
    steps:
      - run: |
          cd /opt/eqproxy-io
          git pull
          docker compose build
          docker compose up -d
          docker compose ps
