name: deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    strategy:
      matrix:
        runs-on: [srv1-osaka, srv2-osaka]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - run: |
          cd /opt/eqproxy-io
          git pull
          docker compose build
          docker compose up -d
          docker compose ps
